//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.logins = new HashSet<login>();
            this.Paiments = new HashSet<Paiment>();
        }
    
        public int idclient { get; set; }
        public Nullable<int> idculb { get; set; }
        public Nullable<int> idSouscategorie { get; set; }
        public string Nomclient { get; set; }
        public string Prenom_cl { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> N_tele { get; set; }
        public Nullable<System.DateTime> datedebut { get; set; }
        public string Genre { get; set; }
        public string Cinclient { get; set; }
        public string cash { get; set; }
        public string card { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual SousCatgorie SousCatgorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiment> Paiments { get; set; }
    }
}
