//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public Nullable<int> idclient { get; set; }
        public int idlogin { get; set; }
        public Nullable<int> idAdmi { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Client Client { get; set; }
    }
}
