//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiment
    {
        public Nullable<int> idclient { get; set; }
        public int idpaiment { get; set; }
        public string Paypal { get; set; }
        public string espace { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
